require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '12.0'

target 'nosync' do
  use_unimodules!
  config = use_native_modules!
 
  use_react_native!(:path => config["reactNativePath"])
  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"


  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  pod 'RNFS', :path => '../node_modules/react-native-fs'

end
